name: build
on: [push]

jobs:
  byz-build:
    name: Coinbase Pro Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build (non-master branch)
        if: github.ref != 'refs/heads/master'
        run: ./gradlew build